- cctv 최근 증가율 = (2018년도+2019년도+2020년도) / 2017년 이전치의 합

# 필요 데이터
 - 자치구 년도별 cctv 설치 현황
 - 서울 통계 서비스 > 주민등록인구(구별) 통계

## cctv 데이터 정리하기
- 데이터 파일 읽기
- Null data 있는지 확인하기
- 1000 단위 구분기호 없애고 정수로 변환하기
- 2021년을 제외한 최근 3개년간의 CCTV 증가율 구하기
- 구분, 총계, 최근증가율 컬럼만 추출하고 컬럼명을 구별, CCTV댓수로 변경하기
- 구 이름에서 공백지우기
- 첫번째 행(계) 지우기

## 인구 데이터 정리하기
 - 데이터 파일 읽기
 - Null data 있는지 확인하기
 - '자치구','계','계.1','계.2','65세 이상 고령자' 컬럼만 추출하고
   이름을 '구별', '인구수','내국인','외국인','고령자'로 변경
 - 1000단위 구분기호 없애고 정수로 변환하기
 - 첫번째 행 지우기
 - '외국인 비율'(외국인/인구수)과 '고령자 비율'(고령자/인구수) 컬럼 만들기

## cctv 데이터와 인구 데이터 합치고 저장하기

- 데이터 합치기
- 구별 컬럼을 인덱스로 만들기
- 합친 데이터를 cctv_pop.csv 로 저장하기

In [115]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [116]:
# 데이터 파일 읽기
filename = '서울시CCTV설치운영현황(자치구)_년도별_211231기준.csv'
cctv = pd.read_csv(filename, skiprows=1, encoding='EUC-KR')
cctv

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,계,"83,557","4,812","1,851","3,434","4,295","6,840","8,708","11,572","10,627","12,267","11,247","7,904"
1,종로구,"1,715",815,NaN,NaN,195,150,0,261,85,9,200,0
2,중 구,"2,447",16,114,87,77,236,240,372,386,155,361,403
3,용산구,"2,611",34,71,234,125,221,298,351,125,307,617,228
4,성동구,"3,829",163,144,208,107,325,255,967,415,490,472,283
5,광진구,"3,211",35,57,100,187,98,52,675,465,712,175,655
6,동대문구,"2,628",4,0,14,16,115,804,814,201,218,223,219
7,중랑구,"3,737",346,21,253,72,132,155,153,174,1049,934,448
8,성북구,"4,602",81,78,170,229,322,594,890,867,714,253,404
9,강북구,"3,090",8,0,22,61,124,251,29,391,1078,656,470
10,도봉구,"1,930",128,22,2,145,172,123,129,222,210,184,593
11,노원구,"2,492",0,87,164,77,514,331,175,216,320,387,221
12,은평구,"4,131",14,3,44,332,329,555,403,635,1057,288,471
13,서대문구,"3,055",730,253,155,108,137,223,356,237,343,397,116
14,마포구,"2,496",23,19,40,112,185,478,365,373,494,299,108
15,양천구,"3,650",71,174,158,134,246,424,577,837,312,346,371
16,강서구,"2,744",54,122,104,202,199,168,506,259,457,356,317
17,구로구,"4,608",852,216,349,187,268,326,540,488,434,415,533
18,금천구,"2,411",0,0,174,80,361,133,196,539,367,513,48
19,영등포구,"4,056",572,136,238,123,209,248,311,658,65,1213,283
20,동작구,"2,306",41,24,25,503,128,253,271,300,322,419,20
21,관악구,"5,149",440,84,431,439,609,622,688,674,595,331,236
22,서초구,"4,082",8,73,79,70,562,504,1041,417,339,433,556
23,강남구,"6,871",69,67,66,580,830,1293,988,745,791,926,516
24,송파구,"2,897",40,59,90,85,214,176,241,541,1073,235,143
25,강동구,"2,809",268,27,227,49,154,202,273,377,356,614,262

In [117]:
# null 값 여부 확인
cctv.isna().sum()

구분          0
총계          0
2012년 이전    0
2012년       1
2013년       1
2014년       0
2015년       0
2016년       0
2017년       0
2018년       0
2019년       0
2020년       0
2021년       0
dtype: int64

In [118]:
# null 값을 0으로 대체
cctv.fillna(0, inplace=True)
cctv

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,계,"83,557","4,812","1,851","3,434","4,295","6,840","8,708","11,572","10,627","12,267","11,247","7,904"
1,종로구,"1,715",815,0,0,195,150,0,261,85,9,200,0
2,중 구,"2,447",16,114,87,77,236,240,372,386,155,361,403
3,용산구,"2,611",34,71,234,125,221,298,351,125,307,617,228
4,성동구,"3,829",163,144,208,107,325,255,967,415,490,472,283
5,광진구,"3,211",35,57,100,187,98,52,675,465,712,175,655
6,동대문구,"2,628",4,0,14,16,115,804,814,201,218,223,219
7,중랑구,"3,737",346,21,253,72,132,155,153,174,1049,934,448
8,성북구,"4,602",81,78,170,229,322,594,890,867,714,253,404
9,강북구,"3,090",8,0,22,61,124,251,29,391,1078,656,470
10,도봉구,"1,930",128,22,2,145,172,123,129,222,210,184,593
11,노원구,"2,492",0,87,164,77,514,331,175,216,320,387,221
12,은평구,"4,131",14,3,44,332,329,555,403,635,1057,288,471
13,서대문구,"3,055",730,253,155,108,137,223,356,237,343,397,116
14,마포구,"2,496",23,19,40,112,185,478,365,373,494,299,108
15,양천구,"3,650",71,174,158,134,246,424,577,837,312,346,371
16,강서구,"2,744",54,122,104,202,199,168,506,259,457,356,317
17,구로구,"4,608",852,216,349,187,268,326,540,488,434,415,533
18,금천구,"2,411",0,0,174,80,361,133,196,539,367,513,48
19,영등포구,"4,056",572,136,238,123,209,248,311,658,65,1213,283
20,동작구,"2,306",41,24,25,503,128,253,271,300,322,419,20
21,관악구,"5,149",440,84,431,439,609,622,688,674,595,331,236
22,서초구,"4,082",8,73,79,70,562,504,1041,417,339,433,556
23,강남구,"6,871",69,67,66,580,830,1293,988,745,791,926,516
24,송파구,"2,897",40,59,90,85,214,176,241,541,1073,235,143
25,강동구,"2,809",268,27,227,49,154,202,273,377,356,614,262

In [119]:
# 1000 단위 구분기호 없애고 정수로 변환하기 (불러올때 정수로 불러옴)
cctv = pd.read_csv(filename, skiprows=1, encoding='EUC-KR',thousands=',')
cctv.fillna(0, inplace=True)
cctv

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,계,83557,4812,1851.0,3434.0,4295,6840,8708,11572,10627,12267,11247,7904
1,종로구,1715,815,0.0,0.0,195,150,0,261,85,9,200,0
2,중 구,2447,16,114.0,87.0,77,236,240,372,386,155,361,403
3,용산구,2611,34,71.0,234.0,125,221,298,351,125,307,617,228
4,성동구,3829,163,144.0,208.0,107,325,255,967,415,490,472,283
5,광진구,3211,35,57.0,100.0,187,98,52,675,465,712,175,655
6,동대문구,2628,4,0.0,14.0,16,115,804,814,201,218,223,219
7,중랑구,3737,346,21.0,253.0,72,132,155,153,174,1049,934,448
8,성북구,4602,81,78.0,170.0,229,322,594,890,867,714,253,404
9,강북구,3090,8,0.0,22.0,61,124,251,29,391,1078,656,470
10,도봉구,1930,128,22.0,2.0,145,172,123,129,222,210,184,593
11,노원구,2492,0,87.0,164.0,77,514,331,175,216,320,387,221
12,은평구,4131,14,3.0,44.0,332,329,555,403,635,1057,288,471
13,서대문구,3055,730,253.0,155.0,108,137,223,356,237,343,397,116
14,마포구,2496,23,19.0,40.0,112,185,478,365,373,494,299,108
15,양천구,3650,71,174.0,158.0,134,246,424,577,837,312,346,371
16,강서구,2744,54,122.0,104.0,202,199,168,506,259,457,356,317
17,구로구,4608,852,216.0,349.0,187,268,326,540,488,434,415,533
18,금천구,2411,0,0.0,174.0,80,361,133,196,539,367,513,48
19,영등포구,4056,572,136.0,238.0,123,209,248,311,658,65,1213,283
20,동작구,2306,41,24.0,25.0,503,128,253,271,300,322,419,20
21,관악구,5149,440,84.0,431.0,439,609,622,688,674,595,331,236
22,서초구,4082,8,73.0,79.0,70,562,504,1041,417,339,433,556
23,강남구,6871,69,67.0,66.0,580,830,1293,988,745,791,926,516
24,송파구,2897,40,59.0,90.0,85,214,176,241,541,1073,235,143
25,강동구,2809,268,27.0,227.0,49,154,202,273,377,356,614,262

In [120]:
# CCTV 데이터 정리하기
cctv['2017년_이전'] = cctv.총계 - cctv['2018년'] - cctv['2019년'] - cctv['2020년'] - cctv['2021년']
cctv['최근증가율'] = ((cctv['2018년']+cctv['2019년']+cctv['2020년']) / cctv['2017년_이전'] * 100).round(2)

In [121]:
# 구분, 총계,최근증가율 컬럼만 추출
cctv = cctv[['구분','총계','최근증가율']]

In [122]:
# 구분,총계 명칭 변경
cctv.rename(columns={'구분':'구별','총계':'CCTV댓수'}, inplace=True)
cctv

      구별  CCTV댓수   최근증가율
0      계   83557   82.24
1    종로구    1715   20.69
2    중 구    2447   78.98
3    용산구    2611   78.64
4    성동구    3829   63.49
5    광진구    3211  112.29
6   동대문구    2628   36.33
7    중랑구    3737  190.55
8    성북구    4602   77.58
9    강북구    3090  429.29
10   도봉구    1930   85.44
11   노원구    2492   68.47
12   은평구    4131  117.86
13  서대문구    3055   49.80
14   마포구    2496   95.42
15   양천구    3650   83.80
16   강서구    2744   79.11
17   구로구    4608   48.83
18   금천구    2411  150.32
19  영등포구    4056  105.39
20   동작구    2306   83.61
21   관악구    5149   48.29
22   서초구    4082   50.88
23   강남구    6871   63.24
24   송파구    2897  204.31
25   강동구    2809  112.25

In [123]:
# 공백 제거
cctv['구별'] = cctv.구별.apply(lambda x: x.replace(' ',''))
cctv

      구별  CCTV댓수   최근증가율
0      계   83557   82.24
1    종로구    1715   20.69
2     중구    2447   78.98
3    용산구    2611   78.64
4    성동구    3829   63.49
5    광진구    3211  112.29
6   동대문구    2628   36.33
7    중랑구    3737  190.55
8    성북구    4602   77.58
9    강북구    3090  429.29
10   도봉구    1930   85.44
11   노원구    2492   68.47
12   은평구    4131  117.86
13  서대문구    3055   49.80
14   마포구    2496   95.42
15   양천구    3650   83.80
16   강서구    2744   79.11
17   구로구    4608   48.83
18   금천구    2411  150.32
19  영등포구    4056  105.39
20   동작구    2306   83.61
21   관악구    5149   48.29
22   서초구    4082   50.88
23   강남구    6871   63.24
24   송파구    2897  204.31
25   강동구    2809  112.25

In [124]:
#첫번째 행 지우기 (계값 없어짐)
cctv.drop([0], inplace=True)
cctv

      구별  CCTV댓수   최근증가율
1    종로구    1715   20.69
2     중구    2447   78.98
3    용산구    2611   78.64
4    성동구    3829   63.49
5    광진구    3211  112.29
6   동대문구    2628   36.33
7    중랑구    3737  190.55
8    성북구    4602   77.58
9    강북구    3090  429.29
10   도봉구    1930   85.44
11   노원구    2492   68.47
12   은평구    4131  117.86
13  서대문구    3055   49.80
14   마포구    2496   95.42
15   양천구    3650   83.80
16   강서구    2744   79.11
17   구로구    4608   48.83
18   금천구    2411  150.32
19  영등포구    4056  105.39
20   동작구    2306   83.61
21   관악구    5149   48.29
22   서초구    4082   50.88
23   강남구    6871   63.24
24   송파구    2897  204.31
25   강동구    2809  112.25

In [130]:
# 데이터 파일 읽기 (1000단위 구분기호 없애고 정수로 변환 작업 병행)
filename = '서울시인구.txt'
pop = pd.read_csv(filename, sep='\t', skiprows=2, thousands=',')
pop

,기간,자치구,세대,계,남자,여자,계.1,남자.1,여자.1,계.2,남자.2,여자.2,세대당인구,65세이상고령자
0,2021,합계,4426007,9736027,4721977,5014050,9509458,4618040,4891418,226569,103937,122632,2.15,1605416
1,2021,종로구,73494,153789,74186,79603,144683,70183,74500,9106,4003,5103,1.97,27818
2,2021,중구,63519,131787,64083,67704,122499,59630,62869,9288,4453,4835,1.93,24392
3,2021,용산구,111036,237285,115085,122200,222953,107210,115743,14332,7875,6457,2.01,39070
4,2021,성동구,134233,292672,142259,150413,285990,139380,146610,6682,2879,3803,2.13,46380
5,2021,광진구,167949,352627,169317,183310,339996,164058,175938,12631,5259,7372,2.02,51723
6,2021,동대문구,168219,352006,172162,179844,337400,166646,170754,14606,5516,9090,2.01,62211
7,2021,중랑구,185712,391885,192903,198982,387350,191112,196238,4535,1791,2744,2.09,71682
8,2021,성북구,195017,440142,211150,228992,430528,207578,222950,9614,3572,6042,2.21,74709
9,2021,강북구,144536,302563,146984,155579,299182,145705,153477,3381,1279,2102,2.07,64333
10,2021,도봉구,138656,319373,155221,164152,317366,154487,162879,2007,734,1273,2.29,64160
11,2021,노원구,217378,514946,247813,267133,510956,246053,264903,3990,1760,2230,2.35,88345
12,2021,은평구,214711,477173,228024,249149,473307,226458,246849,3866,1566,2300,2.20,87241
13,2021,서대문구,143647,315659,149507,166152,304819,145694,159125,10840,3813,7027,2.12,54268
14,2021,마포구,179861,378686,177233,201453,368905,173504,195401,9781,3729,6052,2.05,54582
15,2021,양천구,181404,450487,220537,229950,447302,219214,228088,3185,1323,1862,2.47,68627
16,2021,강서구,271175,579768,278720,301048,574315,276292,298023,5453,2428,3025,2.12,92558
17,2021,구로구,180929,421163,208873,212290,396754,195537,201217,24409,13336,11073,2.19,72611
18,2021,금천구,117595,244891,124110,120781,230811,116527,114284,14080,7583,6497,1.96,41041
19,2021,영등포구,187020,400908,198740,202168,376837,185926,190911,24071,12814,11257,2.01,62516
20,2021,동작구,184812,394364,190241,204123,385483,186426,199057,8881,3815,5066,2.09,66613
21,2021,관악구,276597,499449,250058,249391,485699,243991,241708,13750,6067,7683,1.76,79871
22,2021,서초구,170244,416167,198914,217253,412279,197034,215245,3888,1880,2008,2.42,60678
23,2021,강남구,234233,537800,257280,280520,533042,255047,277995,4758,2233,2525,2.28,78226
24,2021,송파구,282417,663965,319895,344070,658338,317346,340992,5627,2549,3078,2.33,97691
25,2021,강동구,201613,466472,228682,237790,462664,227002,235662,3808,1680,2128,2.29,74070

In [131]:
# Null data 있는지 확인
pop.isna().sum()

기간          0
자치구         0
세대          0
계           0
남자          0
여자          0
계.1         0
남자.1        0
여자.1        0
계.2         0
남자.2        0
여자.2        0
세대당인구       0
65세이상고령자    0
dtype: int64

In [132]:
# 자치구','계','계.1','계.2','65세 이상 고령자' 컬럼만 추출하고 이름을 '구별', '인구수','내국인','외국인','고령자'로 변경
pop = pop[['자치구','계','계.1','계.2','65세이상고령자']]
pop

     자치구        계      계.1     계.2  65세이상고령자
0     합계  9736027  9509458  226569   1605416
1    종로구   153789   144683    9106     27818
2     중구   131787   122499    9288     24392
3    용산구   237285   222953   14332     39070
4    성동구   292672   285990    6682     46380
5    광진구   352627   339996   12631     51723
6   동대문구   352006   337400   14606     62211
7    중랑구   391885   387350    4535     71682
8    성북구   440142   430528    9614     74709
9    강북구   302563   299182    3381     64333
10   도봉구   319373   317366    2007     64160
11   노원구   514946   510956    3990     88345
12   은평구   477173   473307    3866     87241
13  서대문구   315659   304819   10840     54268
14   마포구   378686   368905    9781     54582
15   양천구   450487   447302    3185     68627
16   강서구   579768   574315    5453     92558
17   구로구   421163   396754   24409     72611
18   금천구   244891   230811   14080     41041
19  영등포구   400908   376837   24071     62516
20   동작구   394364   385483    8881     66613
21   관악구   499449   485699   13750     79871
22   서초구   416167   412279    3888     60678
23   강남구   537800   533042    4758     78226
24   송파구   663965   658338    5627     97691
25   강동구   466472   462664    3808     74070

In [133]:
pop.rename(columns={'자치구':'구별','계':'인구수','계.1':'내국인','계.2':'외국인','65세이상고령자':'고령자'}, inplace=True)
pop

      구별      인구수      내국인     외국인      고령자
0     합계  9736027  9509458  226569  1605416
1    종로구   153789   144683    9106    27818
2     중구   131787   122499    9288    24392
3    용산구   237285   222953   14332    39070
4    성동구   292672   285990    6682    46380
5    광진구   352627   339996   12631    51723
6   동대문구   352006   337400   14606    62211
7    중랑구   391885   387350    4535    71682
8    성북구   440142   430528    9614    74709
9    강북구   302563   299182    3381    64333
10   도봉구   319373   317366    2007    64160
11   노원구   514946   510956    3990    88345
12   은평구   477173   473307    3866    87241
13  서대문구   315659   304819   10840    54268
14   마포구   378686   368905    9781    54582
15   양천구   450487   447302    3185    68627
16   강서구   579768   574315    5453    92558
17   구로구   421163   396754   24409    72611
18   금천구   244891   230811   14080    41041
19  영등포구   400908   376837   24071    62516
20   동작구   394364   385483    8881    66613
21   관악구   499449   485699   13750    79871
22   서초구   416167   412279    3888    60678
23   강남구   537800   533042    4758    78226
24   송파구   663965   658338    5627    97691
25   강동구   466472   462664    3808    74070

In [134]:
# 1000 단위 구분기호 없애고 정수로 변환하기 (불러올때 이미 설정함 thousands=',')

In [135]:
# 첫번째 행 지우기 (합계행 없어짐)
pop.drop([0], inplace=True)
pop

      구별     인구수     내국인    외국인    고령자
1    종로구  153789  144683   9106  27818
2     중구  131787  122499   9288  24392
3    용산구  237285  222953  14332  39070
4    성동구  292672  285990   6682  46380
5    광진구  352627  339996  12631  51723
6   동대문구  352006  337400  14606  62211
7    중랑구  391885  387350   4535  71682
8    성북구  440142  430528   9614  74709
9    강북구  302563  299182   3381  64333
10   도봉구  319373  317366   2007  64160
11   노원구  514946  510956   3990  88345
12   은평구  477173  473307   3866  87241
13  서대문구  315659  304819  10840  54268
14   마포구  378686  368905   9781  54582
15   양천구  450487  447302   3185  68627
16   강서구  579768  574315   5453  92558
17   구로구  421163  396754  24409  72611
18   금천구  244891  230811  14080  41041
19  영등포구  400908  376837  24071  62516
20   동작구  394364  385483   8881  66613
21   관악구  499449  485699  13750  79871
22   서초구  416167  412279   3888  60678
23   강남구  537800  533042   4758  78226
24   송파구  663965  658338   5627  97691
25   강동구  466472  462664   3808  74070

In [140]:
# 외국인 비율과 고령자 비율 컬럼 만들기
pop['외국인비율'] = (pop.외국인/pop.인구수*100).round(2)
pop['고령자비율'] = (pop.고령자/pop.인구수*100).round(2)
pop

      구별     인구수     내국인    외국인    고령자  외국인비율  고령자비율
1    종로구  153789  144683   9106  27818   5.92  18.09
2     중구  131787  122499   9288  24392   7.05  18.51
3    용산구  237285  222953  14332  39070   6.04  16.47
4    성동구  292672  285990   6682  46380   2.28  15.85
5    광진구  352627  339996  12631  51723   3.58  14.67
6   동대문구  352006  337400  14606  62211   4.15  17.67
7    중랑구  391885  387350   4535  71682   1.16  18.29
8    성북구  440142  430528   9614  74709   2.18  16.97
9    강북구  302563  299182   3381  64333   1.12  21.26
10   도봉구  319373  317366   2007  64160   0.63  20.09
11   노원구  514946  510956   3990  88345   0.77  17.16
12   은평구  477173  473307   3866  87241   0.81  18.28
13  서대문구  315659  304819  10840  54268   3.43  17.19
14   마포구  378686  368905   9781  54582   2.58  14.41
15   양천구  450487  447302   3185  68627   0.71  15.23
16   강서구  579768  574315   5453  92558   0.94  15.96
17   구로구  421163  396754  24409  72611   5.80  17.24
18   금천구  244891  230811  14080  41041   5.75  16.76
19  영등포구  400908  376837  24071  62516   6.00  15.59
20   동작구  394364  385483   8881  66613   2.25  16.89
21   관악구  499449  485699  13750  79871   2.75  15.99
22   서초구  416167  412279   3888  60678   0.93  14.58
23   강남구  537800  533042   4758  78226   0.88  14.55
24   송파구  663965  658338   5627  97691   0.85  14.71
25   강동구  466472  462664   3808  74070   0.82  15.88

- 데이터 합치기

In [137]:
# data 합치기
df = pd.merge(cctv, pop)
df

      구별  CCTV댓수   최근증가율     인구수     내국인    외국인    고령자  외국인비율  고령자비율
0    종로구    1715   20.69  153789  144683   9106  27818   5.92  18.09
1     중구    2447   78.98  131787  122499   9288  24392   7.05  18.51
2    용산구    2611   78.64  237285  222953  14332  39070   6.04  16.47
3    성동구    3829   63.49  292672  285990   6682  46380   2.28  15.85
4    광진구    3211  112.29  352627  339996  12631  51723   3.58  14.67
5   동대문구    2628   36.33  352006  337400  14606  62211   4.15  17.67
6    중랑구    3737  190.55  391885  387350   4535  71682   1.16  18.29
7    성북구    4602   77.58  440142  430528   9614  74709   2.18  16.97
8    강북구    3090  429.29  302563  299182   3381  64333   1.12  21.26
9    도봉구    1930   85.44  319373  317366   2007  64160   0.63  20.09
10   노원구    2492   68.47  514946  510956   3990  88345   0.77  17.16
11   은평구    4131  117.86  477173  473307   3866  87241   0.81  18.28
12  서대문구    3055   49.80  315659  304819  10840  54268   3.43  17.19
13   마포구    2496   95.42  378686  368905   9781  54582   2.58  14.41
14   양천구    3650   83.80  450487  447302   3185  68627   0.71  15.23
15   강서구    2744   79.11  579768  574315   5453  92558   0.94  15.96
16   구로구    4608   48.83  421163  396754  24409  72611   5.80  17.24
17   금천구    2411  150.32  244891  230811  14080  41041   5.75  16.76
18  영등포구    4056  105.39  400908  376837  24071  62516   6.00  15.59
19   동작구    2306   83.61  394364  385483   8881  66613   2.25  16.89
20   관악구    5149   48.29  499449  485699  13750  79871   2.75  15.99
21   서초구    4082   50.88  416167  412279   3888  60678   0.93  14.58
22   강남구    6871   63.24  537800  533042   4758  78226   0.88  14.55
23   송파구    2897  204.31  663965  658338   5627  97691   0.85  14.71
24   강동구    2809  112.25  466472  462664   3808  74070   0.82  15.88

In [138]:
# '구별' 컬럼을 인덱스로 만들기
df.set_index('구별', inplace=True)
df

      CCTV댓수   최근증가율     인구수     내국인    외국인    고령자  외국인비율  고령자비율
구별
종로구     1715   20.69  153789  144683   9106  27818   5.92  18.09
중구      2447   78.98  131787  122499   9288  24392   7.05  18.51
용산구     2611   78.64  237285  222953  14332  39070   6.04  16.47
성동구     3829   63.49  292672  285990   6682  46380   2.28  15.85
광진구     3211  112.29  352627  339996  12631  51723   3.58  14.67
동대문구    2628   36.33  352006  337400  14606  62211   4.15  17.67
중랑구     3737  190.55  391885  387350   4535  71682   1.16  18.29
성북구     4602   77.58  440142  430528   9614  74709   2.18  16.97
강북구     3090  429.29  302563  299182   3381  64333   1.12  21.26
도봉구     1930   85.44  319373  317366   2007  64160   0.63  20.09
노원구     2492   68.47  514946  510956   3990  88345   0.77  17.16
은평구     4131  117.86  477173  473307   3866  87241   0.81  18.28
서대문구    3055   49.80  315659  304819  10840  54268   3.43  17.19
마포구     2496   95.42  378686  368905   9781  54582   2.58  14.41
양천구     3650   83.80  450487  447302   3185  68627   0.71  15.23
강서구     2744   79.11  579768  574315   5453  92558   0.94  15.96
구로구     4608   48.83  421163  396754  24409  72611   5.80  17.24
금천구     2411  150.32  244891  230811  14080  41041   5.75  16.76
영등포구    4056  105.39  400908  376837  24071  62516   6.00  15.59
동작구     2306   83.61  394364  385483   8881  66613   2.25  16.89
관악구     5149   48.29  499449  485699  13750  79871   2.75  15.99
서초구     4082   50.88  416167  412279   3888  60678   0.93  14.58
강남구     6871   63.24  537800  533042   4758  78226   0.88  14.55
송파구     2897  204.31  663965  658338   5627  97691   0.85  14.71
강동구     2809  112.25  466472  462664   3808  74070   0.82  15.88

In [139]:
# 합친 데이터를 cctv_pop.csv로 저장하기
df.to_csv("cctv_pop.csv", mode='w')

In [141]:
# 검증 차원에서 cctv_pop.csv 에서 데이터 읽어서 확인하기
df2 = pd.read_csv("cctv_pop.csv", index_col=0)
df2

      CCTV댓수   최근증가율     인구수     내국인    외국인    고령자  외국인비율  고령자비율
구별
종로구     1715   20.69  153789  144683   9106  27818   5.92  18.09
중구      2447   78.98  131787  122499   9288  24392   7.05  18.51
용산구     2611   78.64  237285  222953  14332  39070   6.04  16.47
성동구     3829   63.49  292672  285990   6682  46380   2.28  15.85
광진구     3211  112.29  352627  339996  12631  51723   3.58  14.67
동대문구    2628   36.33  352006  337400  14606  62211   4.15  17.67
중랑구     3737  190.55  391885  387350   4535  71682   1.16  18.29
성북구     4602   77.58  440142  430528   9614  74709   2.18  16.97
강북구     3090  429.29  302563  299182   3381  64333   1.12  21.26
도봉구     1930   85.44  319373  317366   2007  64160   0.63  20.09
노원구     2492   68.47  514946  510956   3990  88345   0.77  17.16
은평구     4131  117.86  477173  473307   3866  87241   0.81  18.28
서대문구    3055   49.80  315659  304819  10840  54268   3.43  17.19
마포구     2496   95.42  378686  368905   9781  54582   2.58  14.41
양천구     3650   83.80  450487  447302   3185  68627   0.71  15.23
강서구     2744   79.11  579768  574315   5453  92558   0.94  15.96
구로구     4608   48.83  421163  396754  24409  72611   5.80  17.24
금천구     2411  150.32  244891  230811  14080  41041   5.75  16.76
영등포구    4056  105.39  400908  376837  24071  62516   6.00  15.59
동작구     2306   83.61  394364  385483   8881  66613   2.25  16.89
관악구     5149   48.29  499449  485699  13750  79871   2.75  15.99
서초구     4082   50.88  416167  412279   3888  60678   0.93  14.58
강남구     6871   63.24  537800  533042   4758  78226   0.88  14.55
송파구     2897  204.31  663965  658338   5627  97691   0.85  14.71
강동구     2809  112.25  466472  462664   3808  74070   0.82  15.88